name: Django CI

on:
  push:
    branches: [ "test3" ]
  pull_request:
    branches: [ "test3" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate Environment Variables File for Production
      run: |
        echo "SECRET_KEY=$SECRET_KEY" >> .env.production
        echo "DEBUG=$DEBUG" >> .env.production
      env:
        DEBUG: ${{ variable.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SQLITE_URL: ${{ secrets.SQLITE_URL }}
        CACHE_URL: ${{ secrets.CACHE_URL }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
